export const AVAILABLE_PROPERTIES = [
  {
    group: "Contact activity",
    items: [
      { id: "date_last_meeting", label: "Date of last meeting booked in meetings" },
      { id: "campaign_last_booking", label: "Campaign of last booking in meetings" },
      { id: "medium_last_booking", label: "Medium of last booking in meetings" },
      { id: "source_last_booking", label: "Source of last booking in meetings" },
      { id: "first_conversion_date", label: "First Conversion Date" },
      { id: "first_conversion", label: "First Conversion" },
      { id: "membership_notes", label: "Membership Notes" },
      { id: "status", label: "Status" },
      { id: "last_engagement_date", label: "Last Engagement Date" },
      { id: "recent_sales_email_clicked_date", label: "Recent Sales Email Clicked Date" },
      { id: "recent_sales_email_opened_date", label: "Recent Sales Email Opened Date" },
      { id: "recent_sales_email_replied_date", label: "Recent Sales Email Replied Date" },
      { id: "currently_in_sequence", label: "Currently in Sequence" },
      { id: "message", label: "Message" },
      { id: "last_contacted_2", label: "Last Contacted" },
      { id: "last_activity_date", label: "Last Activity Date" },
      { id: "next_activity_date", label: "Next Activity Date" },
      { id: "number_of_times_contacted", label: "Number of times contacted" },
      { id: "number_of_sales_activities", label: "Number of Sales Activities" }
    ]
  },
  {
    group: "Deal information",
    items: [
      { id: "close_date", label: "Close Date" },
      { id: "days_to_close", label: "Days To Close" },
      { id: "first_deal_created_date", label: "First Deal Created Date" },
      { id: "buying_role", label: "Buying Role" },
      { id: "number_associated_deals", label: "Number of Associated Deals" },
      { id: "recent_deal_amount", label: "Recent Deal Amount" },
      { id: "recent_deal_close_date", label: "Recent Deal Close Date" },
      { id: "total_revenue", label: "Total Revenue" }
    ]
  },
  {
    group: "Order Information",
    items: [
      { id: "first_closed_order_id", label: "First Closed Order ID" },
      { id: "first_order_closed_date", label: "First Order Closed Date" },
      { id: "recent_closed_order_date", label: "Recent Closed Order Date" }
    ]
  },
  {
    group: "Sales properties",
    items: [
      { id: "contact_unworked", label: "Contact unworked" },
      { id: "lead_status_sales", label: "Lead Status" },
      { id: "owner_assigned_date", label: "Owner assigned date" },
      { id: "contact_owner_sales", label: "Contact owner" },
      { id: "Rootline_team", label: "Rootline Team" },
      { id: "Rootline_score", label: "Rootline Score" }
    ]
  },
  {
    group: "Calculated Contact Information",
    items: [
      { id: "member_accessed_private", label: "Member has accessed private content" },
      { id: "registered_member", label: "Registered member" }
    ]
  },
  {
    group: "Contact information",
    items: [
      { id: "street_address", label: "Street Address" },
      { id: "annual_revenue", label: "Annual Revenue" },
      { id: "city", label: "City" },
      { id: "company_name", label: "Company Name" },
      { id: "country_region", label: "Country/Region" },
      { id: "create_date", label: "Create Date" },
      { id: "email_address", label: "Email" },
      { id: "favorite_content_topics", label: "Favorite Content Topics" },
      { id: "fax_number", label: "Fax Number" },
      { id: "first_name", label: "First Name" },
      { id: "chat_assistant_iql_date", label: "Chat Assistant IQL Date" },
      { id: "chat_assistant_source", label: "Chat Assistant Source" },
      { id: "chat_assistant_summary", label: "Chat Assistant:Summary" },
      { id: "enrichment_opt_out", label: "Enrichment opt out" },
      { id: "enrichment_opt_out_timestamp", label: "Enrichment opt out timestamp" },
      { id: "member_email", label: "Member email" },
      { id: "email_confirmed", label: "Email Confirmed" },
      { id: "time_enrolled_registration", label: "Time enrolled in registration follow u..." },
      { id: "registered_at", label: "Registered At" },
      { id: "domain_registration_email", label: "Domain to which registration email w..." },
      { id: "time_registration_email_sent", label: "Time registration email was sent" },
      { id: "country_region_code", label: "Country/Region Code" },
      { id: "created_by_user_id", label: "Created by user ID" },
      { id: "email_domain", label: "Email Domain" },
      { id: "id_first_engagement", label: "ID of first engagement" },
      { id: "inferred_language_codes", label: "Inferred Language Codes" },
      { id: "intent_signals_active", label: "Intent Signals active" },
      { id: "has_been_enriched", label: "Has been enriched" },
      { id: "latest_disqualified_lead_date", label: "Latest Disqualified Lead Date" },
      { id: "latest_open_lead_date", label: "Latest Open Lead Date" },
      { id: "latest_qualified_lead_date", label: "Latest Qualified Lead Date" },
      { id: "last_sequence_ended_date", label: "Last sequence ended date" },
      { id: "last_sequence_enrolled", label: "Last sequence enrolled" },
      { id: "last_sequence_enrolled_date", label: "Last sequence enrolled date" },
      { id: "membership_last_private_content_acc", label: "Membership last private content acc..." },
      { id: "merged_contact_ids", label: "Merged Contact IDs" },
      { id: "record_id", label: "Record ID" },
      { id: "record_source_detail_1", label: "Record source detail 1" },
      { id: "record_source_detail_2", label: "Record source detail 2" },
      { id: "record_source_detail_3", label: "Record source detail 3" },
      { id: "record_source", label: "Record source" },
      { id: "persona", label: "Persona" },
      { id: "prospecting_agent_last_enrolled", label: "Prospecting Agent Last Enrolled" },
      { id: "prospecting_agent_total_enrolled", label: "Prospecting Agent Total Enrolled Cou..." },
      { id: "registration_method", label: "Registration Method" },
      { id: "employment_role", label: "Employment Role" },
      { id: "date_first_engagement", label: "Date of first engagement" },
      { id: "description_first_engagement", label: "Description of first engagement" },
      { id: "type_first_engagement", label: "Type of first engagement" },
      { id: "employment_seniority", label: "Employment Seniority" },
      { id: "number_sequences_enrolled", label: "Number of sequences enrolled" },
      { id: "state_region_code", label: "State/Region Code" },
      { id: "employment_sub_role", label: "Employment Sub Role" },
      { id: "time_between_contact_creation", label: "Time between contact creation and d..." },
      { id: "lead_response_time", label: "Lead response time" },
      { id: "time_to_move_lead_customer", label: "Time to move from lead to customer" },
      { id: "time_to_move_mql_customer", label: "Time to move from marketing qualifi..." },
      { id: "time_to_move_opp_customer", label: "Time to move from opportunity to c..." },
      { id: "time_to_move_sql_customer", label: "Time to move from sales qualified le..." },
      { id: "time_to_move_sub_customer", label: "Time to move from subscriber to cus..." },
      { id: "time_zone", label: "Time Zone" },
      { id: "updated_by_user_id", label: "Updated by user ID" },
      { id: "whatsapp_phone_number", label: "WhatsApp Phone Number" },
      { id: "industry", label: "Industry" },
      { id: "job_title", label: "Job Title" },
      { id: "last_modified_date", label: "Last Modified Date" },
      { id: "last_name", label: "Last Name" },
      { id: "lifecycle_stage_2", label: "Lifecycle Stage" },
      { id: "mobile_phone_number", label: "Mobile Phone Number" },
      { id: "number_of_employees", label: "Number of Employees" },
      { id: "phone_number_2", label: "Phone Number" },
      { id: "preferred_channels", label: "Preferred channels" },
      { id: "salutation", label: "Salutation" },
      { id: "state_region", label: "State/Region" },
      { id: "twitter_username", label: "Twitter Username" },
      { id: "website_url", label: "Website URL" },
      { id: "postal_code", label: "Postal Code" }
    ]
  },
  {
    group: "Social media information",
    items: [
      { id: "linkedin_url", label: "LinkedIn URL" }
    ]
  },
  {
    group: "Web analytics history",
    items: [
      { id: "average_pageviews", label: "Average Pageviews" },
      { id: "first_referring_site", label: "First Referring Site" },
      { id: "time_first_seen", label: "Time First Seen" },
      { id: "first_touch_converting_campaign", label: "First Touch Converting Campaign" },
      { id: "first_page_seen", label: "First Page Seen" },
      { id: "time_first_session", label: "Time of First Session" },
      { id: "last_referring_site", label: "Last Referring Site" },
      { id: "time_last_seen", label: "Time Last Seen" },
      { id: "last_touch_converting_campaign", label: "Last Touch Converting Campaign" },
      { id: "last_page_seen", label: "Last Page Seen" },
      { id: "time_last_session", label: "Time of Last Session" },
      { id: "number_event_completions", label: "Number of event completions" },
      { id: "number_pageviews", label: "Number of Pageviews" },
      { id: "number_sessions", label: "Number of Sessions" },
      { id: "event_revenue", label: "Event Revenue" },
      { id: "original_traffic_source", label: "Original Traffic Source" },
      { id: "original_traffic_source_drilldown1", label: "Original Traffic Source Drill-Down 1" },
      { id: "original_traffic_source_drilldown2", label: "Original Traffic Source Drill-Down 2" },
      { id: "latest_traffic_source", label: "Latest Traffic Source" },
      { id: "latest_traffic_source_drilldown1", label: "Latest Traffic Source Drill-Down 1" },
      { id: "latest_traffic_source_drilldown2", label: "Latest Traffic Source Drill-Down 2" },
      { id: "latest_traffic_source_date", label: "Latest Traffic Source Date" }
    ]
  },
  {
    group: "Conversion information",
    items: [
      { id: "facebook_click_id", label: "Facebook click id" },
      { id: "google_ad_click_id", label: "Google ad click id" },
      { id: "ip_timezone", label: "IP Timezone" },
      { id: "linkedin_click_id", label: "LinkedIn click id" },
      { id: "tiktok_click_id", label: "TikTok click id" },
      { id: "ip_city", label: "IP City" },
      { id: "ip_country", label: "IP Country" },
      { id: "ip_country_code", label: "IP Country Code" },
      { id: "ip_state_region", label: "IP State/Region" },
      { id: "ip_state_code_region_code", label: "IP State Code/Region Code" },
      { id: "number_form_submissions", label: "Number of Form Submissions" },
      { id: "number_unique_forms_submitted", label: "Number of Unique Forms Submitted" },
      { id: "recent_conversion_date", label: "Recent Conversion Date" },
      { id: "recent_conversion", label: "Recent Conversion" }
    ]
  },
  {
    group: "Email information",
    items: [
      { id: "invalid_email_address", label: "Invalid email address" },
      { id: "marketing_emails_bounced", label: "Marketing emails bounced" },
      { id: "marketing_emails_clicked", label: "Marketing emails clicked" },
      { id: "email_address_quarantine_reason", label: "Email address quarantine reason" },
      { id: "marketing_emails_delivered", label: "Marketing emails delivered" },
      { id: "first_marketing_email_click_date", label: "First marketing email click date" },
      { id: "first_marketing_email_open_date", label: "First marketing email open date" },
      { id: "first_marketing_email_reply_date", label: "First marketing email reply date" },
      { id: "first_marketing_email_send_date", label: "First marketing email send date" },
      { id: "email_hard_bounce_reason", label: "Email hard bounce reason" },
      { id: "last_marketing_email_click_date", label: "Last marketing email click date" },
      { id: "last_marketing_email_name", label: "Last marketing email name" },
      { id: "last_marketing_email_open_date", label: "Last marketing email open date" },
      { id: "last_marketing_email_reply_date", label: "Last marketing email reply date" },
      { id: "last_marketing_email_send_date", label: "Last marketing email send date" },
      { id: "marketing_emails_opened", label: "Marketing emails opened" },
      { id: "unsubscribed_from_all_email", label: "Unsubscribed from all email" },
      { id: "opted_out_email_one_to_one", label: "Opted out of email: One to One" },
      { id: "opted_out_email_marketing_info", label: "Opted out of email: Marketing Inform..." },
      { id: "email_address_quarantined", label: "Email Address Quarantined" },
      { id: "email_address_automated_quarantine", label: "Email address automated quarantine ..." },
      { id: "marketing_emails_replied", label: "Marketing emails replied" },
      { id: "sends_since_last_engagement", label: "Sends Since Last Engagement" },
      { id: "email_type", label: "Email type" },
      { id: "marketing_email_confirmation_status", label: "Marketing email confirmation status" },
      { id: "legal_basis_processing", label: "Legal basis for processing contact's ..." },
      { id: "quarantined_emails", label: "Quarantined Emails" }
    ]
  },
  {
    group: "Facebook Ads properties",
    items: [
      { id: "fb_company_size", label: "Company size" },
      { id: "fb_date_of_birth", label: "Date of birth" },
      { id: "fb_degree", label: "Degree" },
      { id: "fb_field_of_study", label: "Field of study" },
      { id: "fb_gender", label: "Gender" },
      { id: "fb_graduation_date", label: "Graduation date" },
      { id: "fb_job_function", label: "Job function" },
      { id: "fb_marital_status", label: "Marital Status" },
      { id: "fb_military_status", label: "Military status" },
      { id: "fb_relationship_status", label: "Relationship Status" },
      { id: "fb_school", label: "School" },
      { id: "fb_seniority", label: "Seniority" },
      { id: "fb_start_date", label: "Start date" },
      { id: "fb_work_email", label: "Work email" }
    ]
  },
  {
    group: "Contact Lifecycle Stage Properties",
    items: [
      { id: "cumulative_time_customer", label: "Cumulative time in \"Customer (Lifecycle Stage)\"" },
      { id: "cumulative_time_evangelist", label: "Cumulative time in \"Evangelist (Lifecycle Stage)\"" },
      { id: "cumulative_time_lead", label: "Cumulative time in \"Lead (Lifecycle Stage)\"" },
      { id: "cumulative_time_mql", label: "Cumulative time in \"Marketing Qualified Lead (Lifecycle Stage)\"" },
      { id: "cumulative_time_opportunity", label: "Cumulative time in \"Opportunity (Lifecycle Stage)\"" },
      { id: "cumulative_time_other", label: "Cumulative time in \"Other (Lifecycle Stage)\"" },
      { id: "cumulative_time_sql", label: "Cumulative time in \"Sales Qualified Lead (Lifecycle Stage)\"" },
      { id: "cumulative_time_subscriber", label: "Cumulative time in \"Subscriber (Lifecycle Stage)\"" },
      { id: "date_entered_current_stage", label: "Date entered current stage" },
      { id: "date_entered_customer", label: "Date entered \"Customer (Lifecycle Stage)\"" },
      { id: "date_entered_evangelist", label: "Date entered \"Evangelist (Lifecycle Stage)\"" },
      { id: "date_entered_lead", label: "Date entered \"Lead (Lifecycle Stage)\"" },
      { id: "date_entered_mql", label: "Date entered \"Marketing Qualified Lead (Lifecycle Stage)\"" },
      { id: "date_entered_opportunity", label: "Date entered \"Opportunity (Lifecycle Stage)\"" },
      { id: "date_entered_other", label: "Date entered \"Other (Lifecycle Stage)\"" },
      { id: "date_entered_sql", label: "Date entered \"Sales Qualified Lead (Lifecycle Stage)\"" },
      { id: "date_entered_subscriber", label: "Date entered \"Subscriber (Lifecycle Stage)\"" },
      { id: "date_exited_customer", label: "Date exited \"Customer (Lifecycle Stage)\"" },
      { id: "date_exited_evangelist", label: "Date exited \"Evangelist (Lifecycle Stage)\"" },
      { id: "date_exited_lead", label: "Date exited \"Lead (Lifecycle Stage)\"" },
      { id: "date_exited_mql", label: "Date exited \"Marketing Qualified Lead (Lifecycle Stage)\"" },
      { id: "date_exited_opportunity", label: "Date exited \"Opportunity (Lifecycle Stage)\"" },
      { id: "date_exited_other", label: "Date exited \"Other (Lifecycle Stage)\"" },
      { id: "date_exited_sql", label: "Date exited \"Sales Qualified Lead (Lifecycle Stage)\"" },
      { id: "date_exited_subscriber", label: "Date exited \"Subscriber (Lifecycle Stage)\"" },
      { id: "latest_time_customer", label: "Latest time in \"Customer (Lifecycle Stage)\"" },
      { id: "latest_time_evangelist", label: "Latest time in \"Evangelist (Lifecycle Stage)\"" },
      { id: "latest_time_lead", label: "Latest time in \"Lead (Lifecycle Stage)\"" },
      { id: "latest_time_mql", label: "Latest time in \"Marketing Qualified Lead (Lifecycle Stage)\"" },
      { id: "latest_time_opportunity", label: "Latest time in \"Opportunity (Lifecycle Stage)\"" },
      { id: "latest_time_other", label: "Latest time in \"Other (Lifecycle Stage)\"" },
      { id: "latest_time_sql", label: "Latest time in \"Sales Qualified Lead (Lifecycle Stage)\"" },
      { id: "latest_time_subscriber", label: "Latest time in \"Subscriber (Lifecycle Stage)\"" },
      { id: "time_in_current_stage", label: "Time in current stage" }
    ]
  }
]
