/**
 * Maps UI column IDs / display names → actual DB column names for the contacts table.
 * Extracted from contacts/page.tsx handleUpdateCell.
 */
export const CONTACT_FIELD_MAPPING: Record<string, string> = {
  'first-name': 'first_name',
  'first_name': 'first_name',
  'First Name': 'first_name',
  'last-name': 'last_name',
  'last_name': 'last_name',
  'Last Name': 'last_name',
  'email': 'email',
  'Email': 'email',
  'phone-number': 'phone',
  'phone': 'phone',
  'Phone': 'phone',
  'mobile_phone': 'mobile_phone',
  'mobile-phone-number': 'mobile_phone',
  'lifecycleStage': 'lifecycle_stage',
  'lifecycle_stage': 'lifecycle_stage',
  'Lifecycle Stage': 'lifecycle_stage',
  'contactOwner': 'owner_id',
  'owner_id': 'owner_id',
  'owner': 'owner_id',
  'Owner': 'owner_id',
  'leadStatus': 'lead_status',
  'lead_status': 'lead_status',
  'Lead Status': 'lead_status',
  'company': 'company_id',
  'Company': 'company_id',
  'company_id': 'company_id',
  'job_title': 'job_title',
  'job-title': 'job_title',
  'Job Title': 'job_title',
  'city': 'city',
  'City': 'city',
  'state': 'state_region',
  'state_region': 'state_region',
  'State/Region': 'state_region',
  'country': 'country',
  'Country/Region': 'country',
  'country_code': 'country_code',
  'industry': 'industry',
  'Industry': 'industry',
  'annual_revenue': 'annual_revenue',
  'annual-revenue': 'annual_revenue',
  'num_employees': 'num_employees',
  'number-of-employees': 'num_employees',
  'persona': 'persona',
  'salutation': 'salutation',
  'pref_lang': 'pref_lang',
  'preferred-language': 'pref_lang',
  'employment_role': 'employment_role',
  'employment_seniority': 'employment_seniority',
  'employment_sub_role': 'employment_sub_role',
  'whatsapp': 'whatsapp',
  'fax': 'fax',
  'website': 'website',
  'website-url': 'website',
  'linkedin_url': 'linkedin_url',
  'linkedin-url': 'linkedin_url',
  'twitter': 'twitter',
  'twitter-username': 'twitter',
  'street_address': 'street_address',
  'postal_code': 'postal_code',
  'timezone': 'timezone',
  'source': 'source',
  'tags': 'tags',
}

/**
 * All real columns in the `contacts` table (not view-only computed columns).
 * Extracted from contacts/page.tsx handleUpdateCell.
 */
export const STANDARD_CONTACT_FIELDS = new Set([
  "email", "phone", "lifecycle_stage", "lead_status", "first_name", "last_name",
  "owner_id", "company_id", "city", "state_region", "country", "country_code",
  "state_region_code", "street_address", "postal_code", "timezone",
  "job_title", "company_name", "industry", "annual_revenue", "num_employees",
  "persona", "salutation", "pref_lang",
  "employment_role", "employment_seniority", "employment_sub_role",
  "mobile_phone", "whatsapp", "fax", "website", "linkedin_url", "twitter",
  "source", "tags", "lead_status",
  "sales_score", "sales_unworked", "sales_region",
  "record_id", "record_source",
  "email_confirmed", "email_domain", "enrichment_opt_out",
  "buying_role", "buying_role_secondary",
  "custom_fields",
])
