export type Locale = 'ar' | 'en'

export const contactContent = {
  ar: {
    nav: {
      cta: 'ابدأ الآن',
    },
    hero: {
      title: 'تواصل مع Rootline CRM',
      subtitle: 'أخبرنا بحاجتك — مساعدنا الذكي سيوجّهك للنموذج المناسب فوراً.',
    },
    smart: {
      label: ' SMART CONTACT',
      replyNote: 'رد خلال يوم عمل واحد',
      title: 'أخبرنا بحاجتك — وسنوجّهك فوراً.',
      description: 'اكتب لنا في سطر واحد. مساعدنا الذكي يفهم طلبك ويفتح النموذج المناسب لك مباشرة — بدون اتصالات، بدون نماط استبيان طويلة.',
      inputPlaceholder: 'صف هدفك في جملة واحدة... مثال: أريد زيادة مبيعات متجر',
      send: 'إرسال',
      smartChat: {
        title: 'استمرار بالمحادثة الذكية',
        badge: 'موصى به',
        description: 'محادثة قصيرة توصلك للمسار الصحيح في أقل من دقيقة.',
        cta: 'ابدأ المحادثة →',
      },
      directForm: {
        title: 'ملء النموذج مباشرة',
        description: 'نموذج منظم بكل التفاصيل — بدون محادثة.',
        cta: 'فتح النموذج →',
      },
      quickTopics: ['تنمية أعمالي', 'الشراكة معنا', 'الانضمام للفريق', 'سؤال'],
      examples: [
        'أحتاج تطوير نظام CRM لشركتي',
        'أريد إدارة صفقاتي وعملائي بشكل منظم',
        'أبحث عن حلول أتمتة المبيعات',
      ],
      form: {
        title: 'طلب اجتماع أو عرض أسعار',
        replyNote: 'رد خلال 24 ساعة في أيام العمل',
        fullName: 'الاسم الكامل *',
        fullNamePlaceholder: 'مثال: أحمد محمد',
        email: 'البريد الإلكتروني *',
        emailPlaceholder: 'ahmed@company.com',
        phone: 'الهاتف / واتساب',
        phonePlaceholder: '+20 100 000 0000',
        company: 'الشركة / العلامة التجارية',
        companyPlaceholder: 'مثال: شركة النور',
        interestedIn: 'مهتم بـ',
        interestedInPlaceholder: 'اختر خدمة...',
        interestedInOptions: ['نظام CRM', 'إدارة مبيعات', 'أتمتة المتابعة', 'تقارير وتحليلات', 'أخرى'],
        timeline: 'الجدول الزمني',
        timelinePlaceholder: "متى تريد البدء؟",
        timelineOptions: ['فوراً', 'خلال أسبوع', 'خلال شهر', 'لم أقرر بعد'],
        goals: 'أخبرنا عن أهدافك *',
        goalsPlaceholder: 'ما الذي تحاول تحقيقه؟ أي سياق عن أعمالك أو جمهورك أو أدائك الحالي مفيد.',
        submit: 'إرسال الطلب',
        submitNote: 'بالإرسال، أنت توافق على التواصل معك بخصوص استفسارك. لن نشارك بياناتك أبداً.',
      },
    },
    faq: {
      sectionTitle: 'FAQ',
      title: 'الأسئلة الأكثر شيوعاً',
      subtitle: 'لا تجد ما تبحث عنه؟ فريقنا جاهز للمساعدة.',
      cta: 'تواصل معنا',
      contact: {
        title: 'محتاج مساعدة مباشرة؟',
        description: 'تواصل معنا مباشرة لإجابات أسرع.',
        phone: '+201272728222',
        email: 'info@saleshub.com',
      },
      items: [
        { question: 'كيف أبدأ في استخدام Rootline CRM؟', answer: 'تواصل معنا من خلال النموذج أدناه أو اتصل بنا مباشرة. سيقوم فريقنا بجدولة مكالمة مجانية لفهم احتياجاتك وعرض الحل المناسب لشركتك.' },
        { question: 'هل يمكنني تجربة النظام قبل الاشتراك؟', answer: 'نعم! نوفر عرضاً تجريبياً مجانيًا لمدة 14 يوم بدون حاجة لبطاقة ائتمان. ستحصل على جميع المميزات لتجربة النظام بالكامل.' },
        { question: 'كم يستغرق إعداد النظام لشركتي؟', answer: 'يعتمد على حجم فريقك وتعقيد احتياجاتك. للفرق الصغيرة (5-10 أعضاء)، نتمكن من الإعداد خلال يوم إلى 3 أيام. للفرق الأكبر، قد يستغرق من أسبوع إلى أسبوعين.' },
        { question: 'هل تقدمون تدريباً للفريق؟', answer: 'نعم! كل اشتراك يشمل جلسة تدريبية مجانية لفريقك. كما نوفر فيديوهات تعليمية ودعم فني مستمر لضمان استخدام النظام بكفاءة.' },
        { question: 'ما هي خيارات الدعم المتاحة؟', answer: 'نقدم دعمًا عبر البريد الإلكتروني والدردشة المباشرة والهاتف. خط الدعم متاح من الأحد إلى الخميس، 9 صباحاً - 6 مساءً. للمشتركين Premium، نوفر دعمًا على مدار الساعة.' },
      ],
    },
    footer: {
      copyright: '© 2026 Rootline CRM. جميع الحقوق محفوظة.',
    },
  },
  en: {
    nav: {
      cta: 'Get Started',
    },
    hero: {
      title: 'Contact Rootline CRM',
      subtitle: 'Tell us what you need — our AI assistant will route you to the right form instantly.',
    },
    smart: {
      label: 'SMART CONTACT',
      replyNote: 'REPLY WITHIN 1 BUSINESS DAY',
      title: 'Tell us what you need — we\'ll route it instantly.',
      description: 'Write to us in one line. Our AI assistant understands your request and opens the right form for you instantly — no calls, no long discovery forms.',
      inputPlaceholder: 'Describe your goal in one sentence... e.g. boost my store\'s sales',
      send: 'Send',
      smartChat: {
        title: 'Continue with smart chat',
        badge: 'RECOMMENDED',
        description: 'Short conversation that routes you to the right path in under a minute.',
        cta: 'Start chat →',
      },
      directForm: {
        title: 'Fill the form directly',
        description: 'A structured form with all the details — no chat required.',
        cta: 'Open form →',
      },
      quickTopics: ['Grow my business', 'Partner with us', 'Join the team', 'Ask a question'],
      examples: [
        'I need a CRM system for my sales team',
        'I want to manage my deals and contacts efficiently',
        'I\'m looking for sales automation solutions',
      ],
      form: {
        title: 'Request a strategy call or quote',
        replyNote: 'Reply within 24h on business days',
        fullName: 'Full name *',
        fullNamePlaceholder: 'e.g. Ahmed Mohamed',
        email: 'Work email *',
        emailPlaceholder: 'ahmed@company.com',
        phone: 'Phone / WhatsApp',
        phonePlaceholder: '+20 100 000 0000',
        company: 'Company / Brand',
        companyPlaceholder: 'e.g. Al Noor Trading',
        interestedIn: 'I\'m interested in',
        interestedInPlaceholder: 'Choose a service...',
        interestedInOptions: ['CRM System', 'Sales Management', 'Follow-up Automation', 'Reports & Analytics', 'Other'],
        timeline: 'Timeline',
        timelinePlaceholder: 'When do you want to start?',
        timelineOptions: ['Immediately', 'Within a week', 'Within a month', 'Not sure yet'],
        goals: 'Tell us about your goals *',
        goalsPlaceholder: 'What are you trying to achieve? Any context about your business, audience, or current performance is helpful.',
        submit: 'Send request',
        submitNote: 'By submitting, you agree to be contacted about your inquiry. We never share your data.',
      },
    },
    faq: {
      sectionTitle: 'FAQ',
      title: 'Frequently Asked Questions',
      subtitle: 'Can\'t find what you\'re looking for? Our team is ready to help.',
      cta: 'Get in touch',
      contact: {
        title: 'Need direct help?',
        description: 'Reach us directly for faster answers.',
        phone: '+201272728222',
        email: 'info@saleshub.com',
      },
      items: [
        { question: 'How do I get started with Rootline CRM?', answer: 'Contact us through the form below or call us directly. Our team will schedule a free call to understand your needs and present the right solution for your company.' },
        { question: 'Can I try the system before subscribing?', answer: 'Yes! We offer a free 14-day trial with no credit card required. You\'ll get access to all features to fully experience the system.' },
        { question: 'How long does it take to set up the system for my company?', answer: 'It depends on your team size and needs complexity. For small teams (5-10 members), we can set up within 1-3 days. For larger teams, it may take 1-2 weeks.' },
        { question: 'Do you offer team training?', answer: 'Yes! Every subscription includes a free training session for your team. We also provide tutorial videos and ongoing technical support to ensure efficient system usage.' },
        { question: 'What support options are available?', answer: 'We offer support via email, live chat, and phone. Support is available Sunday to Thursday, 9 AM - 6 PM. Premium subscribers get 24/7 support.' },
      ],
    },
    footer: {
      copyright: '© 2026 Rootline CRM. All rights reserved.',
    },
  },
} as const
