import { LIFECYCLE_STAGE_OPTIONS } from "./crm-constants"

const LIFECYCLE_LABELS = LIFECYCLE_STAGE_OPTIONS.map(s => s.label)

export const DATE_OPTIONS = [
  { label: "Today", sub: "All of today" },
  { label: "Yesterday", sub: "The previous 24 hour day" },
  { label: "Tomorrow", sub: "The next 24 hour day" },
  { label: "This week", sub: "The current calendar week" },
  { label: "This week so far", sub: "The current calendar week up to now" },
  { label: "Last week", sub: "The previous calendar week" },
  { label: "Next week", sub: "The next calendar week" },
  { label: "This month", sub: "The current calendar month" },
  { label: "This month so far", sub: "The current calendar month up to now" },
  { label: "Last month", sub: "The previous calendar month" },
  { label: "Next month", sub: "The next calendar month" },
  { label: "This quarter", sub: "The current quarter" },
  { label: "This fiscal quarter", sub: "The current fiscal quarter" },
  { label: "This quarter so far", sub: "The current quarter up to now" },
  { label: "This fiscal quarter so far", sub: "The current fiscal quarter up to now" },
  { label: "Last quarter", sub: "The previous full quarter" },
  { label: "Last fiscal quarter", sub: "The previous full fiscal quarter" },
  { label: "Next quarter", sub: "The next full quarter" },
  { label: "Next fiscal quarter", sub: "The next full fiscal quarter" },
  { label: "This year", sub: "The current calendar year" },
  { label: "This fiscal year", sub: "The current fiscal year" },
  { label: "This year so far", sub: "The current calendar year up to now" },
  { label: "This fiscal year so far", sub: "The current fiscal year up to now" },
  { label: "Last year", sub: "The previous calendar year" },
  { label: "Last fiscal year", sub: "The previous fiscal year" },
  { label: "Next year", sub: "The next calendar year" },
  { label: "Next fiscal year", sub: "The next fiscal year" },
  { label: "Last 7 days", sub: "The previous 7 days before today" },
  { label: "Last 14 days", sub: "The previous 14 days before today" },
  { label: "Last 30 days", sub: "The previous 30 days before today" },
  { label: "Last 60 days", sub: "The previous 60 days before today" },
  { label: "Last 90 days", sub: "The previous 90 days before today" },
  { label: "Last 180 days", sub: "The previous 180 days before today" },
  { label: "Last 365 days", sub: "The previous 365 days before today" },
];

export const MORE_FILTERS = [
  {
    category: "Contact activity",
    items: [
      { id: "campaign-of-last-booking", name: "Campaign of last booking in meetings tool", type: "text" },
      { id: "lastActivity", name: "Last activity date", type: "date" },
      { id: "last-contacted", name: "Last contacted", type: "date" },
      { id: "last-engagement-date", name: "Last Engagement Date", type: "date" },
      { id: "medium-of-last-booking", name: "Medium of last booking in meetings tool", type: "text" },
      { id: "membership-notes", name: "Membership notes", type: "text" },
      { id: "message", name: "Message", type: "text" },
      { id: "next-activity-date", name: "Next activity date", type: "date" },
      { id: "now-in-sequence", name: "Now in Sequence", type: "check" },
      { id: "number-of-sales-activities", name: "Number of sales activities", type: "number" },
      { id: "number-of-times-contacted", name: "Number of times contacted", type: "number" },
      { id: "recent-sales-email-open-date", name: "Recent sales email open date", type: "date" },
      { id: "recent-sales-email-replied-date", name: "Recent sales email replied date", type: "date" },
      { id: "recent-sales-emails-clicked-date", name: "Recent sales emails clicked date", type: "date" },
      { id: "source-of-last-booking", name: "Source of last booking in meetings tool", type: "text" },
      { id: "status", name: "Status", type: "check" },
    ]
  },
  {
    category: "Deal information",
    items: [
      { id: "buying-role", name: "Buying Role", type: "check" },
      { id: "close-date", name: "Close date", type: "date" },
      { id: "days-to-close", name: "Days to Close", type: "number" },
      { id: "first-deal-created-date", name: "First deal created date", type: "date" },
      { id: "number-of-associated-deals", name: "Number of Associated Deals", type: "arrows" },
      { id: "recent-deal-amount", name: "Recent deal amount", type: "number" },
      { id: "recent-deal-close-date", name: "Recent deal close date", type: "date" },
      { id: "total-revenue", name: "Total revenue", type: "number" },
    ]
  },
  {
    category: "Order Information",
    items: [
      { id: "first-closed-order-id", name: "First Closed Order ID", type: "number" },
      { id: "first-order-closed-date", name: "First Order Closed Date", type: "date" },
      { id: "recent-closed-order-date", name: "Recent Closed Order Date", type: "date" },
    ]
  },
  {
    category: "Sales properties",
    items: [
      { id: "contactOwner", name: "Contact owner", type: "check" },
      { id: "contact-unworked", name: "Contact unworked", type: "fx" },
      { id: "Rootline-score", name: "Rootline score", type: "fx" },
      { id: "Rootline-team", name: "Rootline team", type: "check" },
      { id: "leadStatus", name: "Lead status", type: "check" },
      { id: "owner-assigned-date", name: "Owner assigned date", type: "date" },
    ]
  },
  {
    category: "Calculated Contact Information",
    items: [
      { id: "member-has-accessed-private-content", name: "Member has accessed private content", type: "fx" },
      { id: "registered-member", name: "Registered member", type: "fx" },
    ]
  },
  {
    category: "Contact information",
    items: [
      { id: "annual-revenue", name: "Annual revenue", type: "text" },
      { id: "associated-records", name: "Associated records", type: "text" },
      { id: "chat-assistant-iql-date", name: "Chat Assistant IQL Date", type: "date" },
      { id: "chat-assistant-source", name: "Chat Assistant Source", type: "check" },
      { id: "chat-assistant-summary", name: "Chat Assistant: Summary", type: "code" },
      { id: "city", name: "City", type: "text" },
      { id: "company-name", name: "Company name", type: "text" },
      { id: "country-region", name: "Country/Region", type: "text" },
      { id: "country-region-code", name: "Country/Region Code", type: "text" },
      { id: "createDate", name: "Create date", type: "date" },
      { id: "created-by-user-id", name: "Created by user ID", type: "check" },
      { id: "date-of-first-engagement", name: "Date of first engagement", type: "date" },
      { id: "description-of-first-engagement", name: "Description of first engagement", type: "check" },
      { id: "domain-to-which-registration-email-was-sent", name: "Domain to which registration email was s...", type: "text" },
      { id: "email", name: "Email", type: "text" },
      { id: "email-confirmed", name: "Email Confirmed", type: "check" },
      { id: "email-domain", name: "Email Domain", type: "text" },
      { id: "employment-role", name: "Employment Role", type: "check" },
      { id: "employment-seniority", name: "Employment Seniority", type: "check" },
      { id: "employment-sub-role", name: "Employment Sub Role", type: "check" },
      { id: "enrichment-opt-out", name: "Enrichment opt out", type: "check" },
      { id: "enrichment-opt-out-timestamp", name: "Enrichment opt out timestamp", type: "date" },
      { id: "favorite-content-topics", name: "Favorite Content Topics", type: "check" },
      { id: "fax-number", name: "Fax number", type: "number" },
      { id: "first-name", name: "First name", type: "text" },
      { id: "form-submission", name: "Form submission", type: "check" },
      { id: "has-been-enriched", name: "Has been enriched", type: "check" },
      { id: "id-of-first-engagement", name: "ID of first engagement", type: "number" },
      { id: "import", name: "Import", type: "check" },
      { id: "industry", name: "Industry", type: "text" },
      { id: "inferred-language-codes", name: "Inferred Language Codes", type: "check" },
      { id: "intent-signals-active", name: "Intent Signals active", type: "check" },
      { id: "job-title", name: "Job title", type: "text" },
      { id: "last-modified-date", name: "Last modified date", type: "date" },
      { id: "last-name", name: "Last name", type: "text" },
      { id: "last-sequence-ended-date", name: "Last sequence ended date", type: "date" },
      { id: "last-sequence-enrolled", name: "Last sequence enrolled", type: "check" },
      { id: "last-sequence-enrolled-date", name: "Last sequence enrolled date", type: "date" },
      { id: "latest-disqualified-lead-date", name: "Latest Disqualified Lead Date", type: "arrows" },
      { id: "latest-open-lead-date", name: "Latest Open Lead Date", type: "arrows" },
      { id: "latest-qualified-lead-date", name: "Latest Qualified Lead Date", type: "arrows" },
      { id: "lead-response-time", name: "Lead response time", type: "number" },
      { id: "lifecycleStage", name: "Lifecycle stage", type: "property", options: LIFECYCLE_LABELS },
      { id: "member-email", name: "Member email", type: "text" },
      { id: "membership-last-private-content-access", name: "Membership last private content access ...", type: "date" },
      { id: "merged-contact-ids", name: "Merged Contact IDs", type: "check" },
      { id: "mobile-phone-number", name: "Mobile phone number", type: "number" },
      { id: "number-of-employees", name: "Number of employees", type: "check" },
      { id: "number-of-sequences-enrolled", name: "Number of sequences enrolled", type: "number" },
      { id: "persona", name: "Persona", type: "check" },
      { id: "phone-number", name: "Phone number", type: "number" },
      { id: "postal-code", name: "Postal code", type: "text" },
      { id: "preferred-channels", name: "Preferred channels", type: "check" },
      { id: "preferred-language", name: "Preferred language", type: "check" },
      { id: "primary-associated-company", name: "Primary associated company", type: "check" },
      { id: "prospecting-agent-last-enrolled", name: "Prospecting Agent Last Enrolled", type: "arrows" },
      { id: "prospecting-agent-total-enrolled-count", name: "Prospecting Agent Total Enrolled Count", type: "arrows" },
      { id: "record-id", name: "Record ID", type: "number" },
      { id: "record-source", name: "Record source", type: "check" },
      { id: "record-source-detail-1", name: "Record source detail 1", type: "text" },
      { id: "record-source-detail-2", name: "Record source detail 2", type: "text" },
      { id: "record-source-detail-3", name: "Record source detail 3", type: "text" },
      { id: "registered-at", name: "Registered at", type: "date" },
      { id: "registration-method", name: "Registration Method", type: "text" },
      { id: "salutation", name: "Salutation", type: "text" },
      { id: "segment-list-membership", name: "Segment (List) membership", type: "check" },
      { id: "state-region", name: "State/Region", type: "text" },
      { id: "state-region-code", name: "State/Region Code", type: "text" },
      { id: "street-address", name: "Street address", type: "text" },
      { id: "time-enrolled-in-registration-follow-up-email", name: "Time enrolled in registration follow up em...", type: "date" },
      { id: "time-registration-email-was-sent", name: "Time registration email was sent", type: "date" },
      { id: "time-zone", name: "Time zone", type: "check" },
      { id: "twitter-username", name: "Twitter username", type: "text" },
      { id: "type-of-first-engagement", name: "Type of first engagement", type: "check" },
      { id: "updated-by-user-id", name: "Updated by user ID", type: "check" },
      { id: "website-url", name: "Website URL", type: "link" },
      { id: "whatsapp-phone-number", name: "WhatsApp Phone Number", type: "number" },
    ]
  },
  {
    category: "Social & Ads",
    items: [
      { id: "linkedin-url", name: "LinkedIn URL", type: "link" },
      { id: "facebook-click-id", name: "Facebook click id", type: "text" },
    ]
  },
  {
    category: "Web analytics history",
    items: [
      { id: "average-page-views", name: "Average page views", type: "number" },
      { id: "event-revenue", name: "Event Revenue", type: "number" },
      { id: "first-page-seen", name: "First page seen", type: "link" },
      { id: "first-referring-site", name: "First referring site", type: "text" },
      { id: "first-touch-converting-campaign", name: "First touch converting campaign", type: "check" },
      { id: "last-page-seen", name: "Last page seen", type: "link" },
      { id: "last-referring-site", name: "Last referring site", type: "text" },
      { id: "last-touch-converting-campaign", name: "Last touch converting campaign", type: "check" },
      { id: "latest-traffic-source", name: "Latest Traffic Source", type: "check" },
      { id: "latest-traffic-source-date", name: "Latest Traffic Source Date", type: "date" },
      { id: "latest-traffic-source-drill-down-1", name: "Latest Traffic Source Drill-Down 1", type: "text" },
      { id: "latest-traffic-source-drill-down-2", name: "Latest Traffic Source Drill-Down 2", type: "text" },
      { id: "number-of-event-completions", name: "Number of event completions", type: "number" },
      { id: "number-of-page-views", name: "Number of page views", type: "number" },
      { id: "number-of-sessions", name: "Number of sessions", type: "number" },
      { id: "original-traffic-source", name: "Original Traffic Source", type: "check" },
      { id: "original-traffic-source-drill-down-1", name: "Original Traffic Source Drill-Down 1", type: "text" },
      { id: "original-traffic-source-drill-down-2", name: "Original Traffic Source Drill-Down 2", type: "text" },
      { id: "time-first-seen", name: "Time first seen", type: "date" },
      { id: "time-last-seen", name: "Time last seen", type: "date" },
      { id: "time-of-first-session", name: "Time of first session", type: "date" },
      { id: "time-of-last-session", name: "Time of last session", type: "date" },
    ]
  },
  {
    category: "Conversion information",
    items: [
      { id: "google-ad-click-id", name: "Google ad click ID", type: "text" },
      { id: "ip-city", name: "IP city", type: "text" },
      { id: "ip-country", name: "IP country", type: "text" },
      { id: "ip-country-code", name: "IP country code", type: "text" },
      { id: "ip-state-region", name: "IP state/region", type: "text" },
      { id: "ip-state-region-code", name: "IP state/region code", type: "text" },
      { id: "ip-time-zone", name: "IP time zone", type: "text" },
      { id: "linkedin-click-id", name: "LinkedIn click id", type: "text" },
      { id: "number-of-form-submissions", name: "Number of form submissions", type: "number" },
      { id: "number-of-unique-forms-submitted", name: "Number of unique forms submitted", type: "number" },
      { id: "recent-conversion", name: "Recent conversion", type: "text" },
      { id: "recent-conversion-date", name: "Recent conversion date", type: "date" },
      { id: "tiktok-click-id", name: "TikTok click id", type: "text" },
    ]
  },
  {
    category: "Email information",
    items: [
      { id: "email-quarantine-reason-auto", name: "Email address automated quarantine rea...", type: "check" },
      { id: "email-quarantine-reason", name: "Email address quarantine reason", type: "check" },
      { id: "email-quarantined", name: "Email address quarantined", type: "check" },
      { id: "email-hard-bounce-reason", name: "Email hard bounce reason", type: "check" },
      { id: "email-type", name: "Email type", type: "check" },
      { id: "first-marketing-email-click-date", name: "First marketing email click date", type: "date" },
      { id: "first-marketing-email-open-date", name: "First marketing email open date", type: "date" },
      { id: "first-marketing-email-reply-date", name: "First marketing email reply date", type: "date" },
      { id: "first-marketing-email-send-date", name: "First marketing email send date", type: "date" },
      { id: "invalid-email-address", name: "Invalid email address", type: "check" },
      { id: "last-marketing-email-click-date", name: "Last marketing email click date", type: "date" },
      { id: "last-marketing-email-name", name: "Last marketing email name", type: "text" },
      { id: "last-marketing-email-open-date", name: "Last marketing email open date", type: "date" },
      { id: "last-marketing-email-reply-date", name: "Last marketing email reply date", type: "date" },
      { id: "last-marketing-email-send-date", name: "Last marketing email send date", type: "date" },
      { id: "legal-basis-for-processing", name: "Legal basis for processing contact's data", type: "check" },
      { id: "marketing-email-confirmation-status", name: "Marketing email confirmation status", type: "check" },
      { id: "marketing-emails-bounced", name: "Marketing emails bounced", type: "number" },
      { id: "marketing-emails-clicked", name: "Marketing emails clicked", type: "number" },
      { id: "marketing-emails-delivered", name: "Marketing emails delivered", type: "number" },
      { id: "marketing-emails-opened", name: "Marketing emails opened", type: "number" },
      { id: "marketing-emails-replied", name: "Marketing emails replied", type: "number" },
      { id: "opted-out-marketing", name: "Opted out of email marketing information", type: "check" },
      { id: "opted-out-one-to-one", name: "Opted out of email: One to one", type: "check" },
      { id: "quarantined-emails", name: "Quarantined Emails", type: "text" },
      { id: "sends-since-last-engagement", name: "Sends since last engagement", type: "number" },
      { id: "unsubscribed-from-all", name: "Unsubscribed from all email", type: "check" },
    ]
  },
  {
    category: "Facebook Ads properties",
    items: [
      { id: "fb-company-size", name: "Company size", type: "text" },
      { id: "fb-dob", name: "Date of birth", type: "text" },
      { id: "fb-degree", name: "Degree", type: "text" },
      { id: "fb-field-of-study", name: "Field of study", type: "text" },
      { id: "fb-gender", name: "Gender", type: "text" },
      { id: "fb-graduation-date", name: "Graduation date", type: "text" },
      { id: "fb-job-function", name: "Job function", type: "text" },
      { id: "fb-marital-status", name: "Marital status", type: "text" },
      { id: "fb-military-status", name: "Military status", type: "text" },
      { id: "fb-relationship-status", name: "Relationship status", type: "text" },
      { id: "fb-school", name: "School", type: "text" },
      { id: "fb-seniority", name: "Seniority", type: "text" },
      { id: "fb-start-date", name: "Start date", type: "text" },
      { id: "fb-work-email", name: "Work email", type: "text" },
    ]
  },
  {
    category: "Contact Lifecycle Stage Properties",
    items: [
      { id: "date-entered-customer", name: "Date entered \"Customer (Lifecycle Stage ...", type: "date" },
      { id: "date-entered-evangelist", name: "Date entered \"Evangelist (Lifecycle Stage...", type: "date" },
      { id: "date-entered-lead", name: "Date entered \"Lead (Lifecycle Stage Pipe...", type: "date" },
      { id: "date-entered-marketing-qualified-lead", name: "Date entered \"Marketing Qualified Lead\"", type: "date" },
      { id: "date-entered-opportunity", name: "Date entered \"Opportunity (Lifecycle Sta...", type: "date" },
      { id: "date-entered-other", name: "Date entered \"Other (Lifecycle Stage Pipe...", type: "date" },
      { id: "date-entered-sales-qualified-lead", name: "Date entered \"Sales Qualified Lead\"", type: "date" },
      { id: "date-entered-subscriber", name: "Date entered \"Subscriber (Lifecycle Stag...", type: "date" },
      { id: "date-exited-customer", name: "Date exited \"Customer (Lifecycle Stage P...", type: "date" },
      { id: "date-exited-evangelist", name: "Date exited \"Evangelist (Lifecycle Stage...", type: "date" },
      { id: "date-exited-lead", name: "Date exited \"Lead (Lifecycle Stage Pipel...", type: "date" },
      { id: "date-exited-marketing-qualified-lead", name: "Date exited \"Marketing Qualified Lead\"", type: "date" },
      { id: "date-exited-opportunity", name: "Date exited \"Opportunity (Lifecycle Stag...", type: "date" },
      { id: "date-exited-other", name: "Date exited \"Other (Lifecycle Stage Pipe...", type: "date" },
      { id: "date-exited-sales-qualified-lead", name: "Date exited \"Sales Qualified Lead\"", type: "date" },
      { id: "date-exited-subscriber", name: "Date exited \"Subscriber (Lifecycle Stage...", type: "date" },
    ]
  }
];

export const COMPANY_MORE_FILTERS = [
  {
    category: "Company activity",
    items: [
      { id: "campaign-of-last-booking", name: "Campaign of last booking in meetings tool", type: "text" },
      { id: "date-of-last-meeting-booked", name: "Date of last meeting booked in meetings ...", type: "date" },
      { id: "last-booked-meeting-date", name: "Last Booked Meeting Date", type: "date" },
      { id: "last-contacted", name: "Last contacted", type: "date" },
      { id: "last-engagement-date", name: "Last Engagement Date", type: "date" },
      { id: "last-logged-call-date", name: "Last Logged Call Date", type: "date" },
      { id: "last-logged-outgoing-email-date", name: "Last Logged Outgoing Email Date", type: "arrows" },
      { id: "last-modified-date", name: "Last modified date", type: "date" },
      { id: "last-open-task-date", name: "Last Open Task Date", type: "date" },
      { id: "next-activity-date", name: "Next activity date", type: "date" },
      { id: "number-of-times-contacted", name: "Number of times contacted", type: "number" },
      { id: "source-of-last-booking", name: "Source of last booking in meetings tool", type: "text" },
    ]
  },
  {
    category: "Deal information",
    items: [
      { id: "first-deal-created-date", name: "First deal created date", type: "date" },
      { id: "number-of-associated-deals", name: "Number of Associated Deals", type: "arrows" },
      { id: "number-of-open-deals", name: "Number of open deals", type: "number" },
      { id: "recent-deal-amount", name: "Recent deal amount", type: "number" },
      { id: "recent-deal-close-date", name: "Recent deal close date", type: "date" },
      { id: "total-open-deal-value", name: "Total open deal value", type: "number" },
    ]
  },
  {
    category: "Sales properties",
    items: [
      { id: "Rootline-team", name: "Rootline team", type: "check" },
      { id: "owner-assigned-date", name: "Owner assigned date", type: "date" },
    ]
  },
  {
    category: "Company Signals",
    items: [
      { id: "intent-signals-active", name: "Intent Signals active", type: "check" },
      { id: "recent-intent-signals", name: "Recent Intent Signals", type: "check" },
    ]
  },
  {
    category: "Company information",
    items: [
      { id: "about-us", name: "About us", type: "text" },
      { id: "annual-revenue", name: "Annual revenue", type: "number" },
      { id: "associated-records", name: "Associated records", type: "text" },
      { id: "city", name: "City", type: "text" },
      { id: "close-date", name: "Close date", type: "date" },
      { id: "company-domain-name", name: "Company domain name", type: "link" },
      { id: "company-keywords", name: "Company Keywords", type: "check" },
      { id: "company-name", name: "Company name", type: "text" },
      { id: "country-region", name: "Country/Region", type: "text" },
      { id: "country-region-code", name: "Country/Region Code", type: "text" },
      { id: "created-by-user-id", name: "Created by user ID", type: "check" },
      { id: "days-to-close", name: "Days to Close", type: "fx" },
      { id: "description", name: "Description", type: "text" },
      { id: "employee-range", name: "Employee range", type: "text" },
      { id: "first-contact-create-date", name: "First contact create date", type: "date" },
      { id: "has-been-enriched", name: "Has been enriched", type: "check" },
      { id: "import", name: "Import", type: "check" },
      { id: "industry", name: "Industry", type: "check" },
      { id: "industry-group", name: "Industry group", type: "text" },
      { id: "is-public", name: "Is public", type: "check" },
      { id: "last-touch-converting-campaign", name: "Last touch converting campaign", type: "check" },
      { id: "latest-traffic-source", name: "Latest Traffic Source", type: "check" },
      { id: "latest-traffic-source-data-1", name: "Latest Traffic Source Data 1", type: "text" },
      { id: "latest-traffic-source-data-2", name: "Latest Traffic Source Data 2", type: "text" },
      { id: "latest-traffic-source-timestamp", name: "Latest Traffic Source Timestamp", type: "date" },
      { id: "lifecycle-stage", name: "Lifecycle stage", type: "property", options: LIFECYCLE_LABELS },
      { id: "linkedin-handle", name: "Linkedin handle", type: "text" },
      { id: "logo-url", name: "Logo URL", type: "link" },
      { id: "medium-of-last-booking", name: "Medium of last booking in meetings tool", type: "text" },
      { id: "merged-company-ids", name: "Merged Company IDs", type: "check" },
      { id: "number-of-associated-contacts", name: "Number of associated contacts", type: "arrows" },
      { id: "number-of-child-companies", name: "Number of child companies", type: "number" },
      { id: "number-of-employees", name: "Number of employees", type: "number" },
      { id: "original-traffic-source", name: "Original Traffic Source", type: "check" },
      { id: "original-traffic-source-drill-down-1", name: "Original Traffic Source Drill-Down 1", type: "text" },
      { id: "original-traffic-source-drill-down-2", name: "Original Traffic Source Drill-Down 2", type: "text" },
      { id: "parent-company", name: "Parent company", type: "check" },
      { id: "phone-number", name: "Phone number", type: "number" },
      { id: "postal-code", name: "Postal code", type: "text" },
      { id: "quick-context", name: "Quick context", type: "code" },
      { id: "record-id", name: "Record ID", type: "number" },
      { id: "record-source", name: "Record source", type: "check" },
      { id: "record-source-detail-1", name: "Record source detail 1", type: "text" },
      { id: "record-source-detail-2", name: "Record source detail 2", type: "text" },
      { id: "record-source-detail-3", name: "Record source detail 3", type: "text" },
      { id: "revenue-range", name: "Revenue range", type: "text" },
      { id: "segment-list-membership", name: "Segment (List) membership", type: "check" },
      { id: "state-region", name: "State/Region", type: "text" },
      { id: "state-region-code", name: "State/Region Code", type: "text" },
      { id: "street-address", name: "Street address", type: "text" },
      { id: "street-address-2", name: "Street address 2", type: "text" },
      { id: "time-zone", name: "Time zone", type: "text" },
      { id: "total-money-raised", name: "Total money raised", type: "text" },
      { id: "total-revenue", name: "Total revenue", type: "arrows" },
      { id: "type", name: "Type", type: "check" },
      { id: "updated-by-user-id", name: "Updated by user ID", type: "check" },
      { id: "web-technologies", name: "Web technologies", type: "check" },
      { id: "website-url", name: "Website URL", type: "link" },
      { id: "year-founded", name: "Year founded", type: "text" },
    ]
  },
  {
    category: "Social media information",
    items: [
      { id: "facebook-company-page", name: "Facebook company page", type: "text" },
      { id: "facebook-fans", name: "Facebook fans", type: "number" },
      { id: "google-plus-page", name: "Google plus page", type: "text" },
      { id: "linkedin-bio", name: "LinkedIn bio", type: "text" },
      { id: "linkedin-company-page", name: "LinkedIn company page", type: "text" },
      { id: "twitter-bio", name: "Twitter bio", type: "text" },
      { id: "twitter-followers", name: "Twitter followers", type: "number" },
      { id: "twitter-handle", name: "Twitter handle", type: "text" },
    ]
  },
  {
    category: "Web analytics history",
    items: [
      { id: "number-of-page-views", name: "Number of page views", type: "number" },
      { id: "number-of-sessions", name: "Number of sessions", type: "number" },
      { id: "time-first-seen", name: "Time first seen", type: "date" },
      { id: "time-last-seen", name: "Time last seen", type: "date" },
      { id: "time-of-last-session", name: "Time of last session", type: "date" },
    ]
  },
  {
    category: "Conversion information",
    items: [
      { id: "first-conversion", name: "First conversion", type: "text" },
      { id: "first-conversion-date", name: "First conversion date", type: "date" },
      { id: "first-touch-converting-campaign", name: "First touch converting campaign", type: "check" },
      { id: "number-of-form-submissions", name: "Number of form submissions", type: "number" },
      { id: "recent-conversion", name: "Recent conversion", type: "text" },
      { id: "recent-conversion-date", name: "Recent conversion date", type: "date" },
      { id: "time-of-first-session", name: "Time of first session", type: "date" },
    ]
  },
  {
    category: "Target accounts information",
    items: [
      { id: "ideal-customer-profile-tier", name: "Ideal Customer Profile Tier", type: "check" },
      { id: "number-of-blockers", name: "Number of blockers", type: "number" },
      { id: "number-of-contacts-with-buying-role", name: "Number of contacts with a buying role", type: "number" },
      { id: "number-of-decision-makers", name: "Number of decision makers", type: "number" },
      { id: "target-account", name: "Target Account", type: "check" },
    ]
  }
];

export const DEAL_MORE_FILTERS = [
  {
    category: "Deal activity",
    items: [
      { id: "campaign-of-last-booking", name: "Campaign of last booking in meetings tool", type: "text" },
      { id: "closed-lost-reason", name: "Closed lost reason", type: "text" },
      { id: "closed-won-reason", name: "Closed won reason", type: "text" },
      { id: "date-of-last-meeting-booked", name: "Date of last meeting booked in meetings tool", type: "date" },
      { id: "deal-stage", name: "Deal stage", type: "check" },
      { id: "has-last-conversation-follow-ups", name: "Has Last Conversation Follow Ups", type: "fx" },
      { id: "is-closed-lost", name: "Is closed lost", type: "fx" },
      { id: "is-closed-won", name: "Is Closed Won", type: "fx" },
      { id: "last-activity-date", name: "Last activity date", type: "date" },
      { id: "last-contacted", name: "Last contacted", type: "date" },
      { id: "last-conversation-with-follow-ups", name: "Last conversation with follow-ups", type: "text" },
      { id: "last-gs-shared-message", name: "Last GS Shared Message", type: "arrows" },
      { id: "last-modified-date", name: "Last modified date", type: "date" },
      { id: "last-partner-shared-message-date", name: "Last Partner Shared Message Date", type: "arrows" },
      { id: "latest-approval-status", name: "Latest Approval Status", type: "text" },
      { id: "medium-of-last-booking", name: "Medium of last booking in meetings tool", type: "text" },
      { id: "next-activity-date", name: "Next activity date", type: "date" },
      { id: "number-of-sales-activities", name: "Number of sales activities", type: "number" },
      { id: "number-of-times-contacted", name: "Number of times contacted", type: "number" },
      { id: "owner-assigned-date", name: "Owner assigned date", type: "date" },
      { id: "pipeline", name: "Pipeline", type: "check" },
      { id: "source-of-last-booking", name: "Source of last booking in meetings tool", type: "text" },
    ]
  },
  {
    category: "Deal revenue",
    items: [
      { id: "amount", name: "Amount", type: "number" },
      { id: "amount-in-company-currency", name: "Amount in company currency", type: "fx" },
      { id: "annual-contract-value", name: "Annual contract value", type: "number" },
      { id: "annual-recurring-revenue", name: "Annual recurring revenue", type: "number" },
      { id: "exchange-rate", name: "Exchange rate", type: "number" },
      { id: "monthly-recurring-revenue", name: "Monthly recurring revenue", type: "number" },
      { id: "total-contract-value", name: "Total contract value", type: "number" },
    ]
  },
  {
    category: "Deal information",
    items: [
      { id: "associated-company", name: "Associated company", type: "text" },
      { id: "associated-contact", name: "Associated contact", type: "text" },
      { id: "associated-records", name: "Associated records", type: "text" },
      { id: "close-date", name: "Close date", type: "date" },
      { id: "closed-won-count", name: "Closed won count", type: "fx" },
      { id: "create-date", name: "Create date", type: "date" },
      { id: "created-by-user-id", name: "Created by user ID", type: "check" },
      { id: "days-to-close", name: "Days to Close", type: "fx" },
      { id: "deal-collaborator", name: "Deal Collaborator", type: "check" },
      { id: "deal-description", name: "Deal Description", type: "text" },
      { id: "deal-name", name: "Deal name", type: "text" },
      { id: "deal-owner", name: "Deal owner", type: "check" },
      { id: "deal-probability", name: "Deal probability", type: "number" },
      { id: "deal-type", name: "Deal type", type: "check" },
      { id: "forecast-amount", name: "Forecast amount", type: "number" },
      { id: "forecast-category", name: "Forecast category", type: "check" },
      { id: "forecast-probability", name: "Forecast probability", type: "number" },
      { id: "Rootline-team", name: "Rootline team", type: "check" },
      { id: "import", name: "Import", type: "check" },
      { id: "is-closed-numeric", name: "Is Closed (numeric)", type: "fx" },
      { id: "is-deal-closed", name: "Is Deal Closed?", type: "fx" },
      { id: "is-open-numeric", name: "Is Open (numeric)", type: "fx" },
      { id: "merged-deal-ids", name: "Merged Deal IDs", type: "check" },
      { id: "next-activity", name: "Next Activity", type: "text" },
      { id: "next-meeting", name: "Next Meeting", type: "number" },
      { id: "next-meeting-name", name: "Next Meeting Name", type: "text" },
      { id: "next-meeting-start-time", name: "Next Meeting Start Time", type: "date" },
      { id: "next-step", name: "Next step", type: "text" },
      { id: "number-of-associated-contacts", name: "Number of associated contacts", type: "arrows" },
      { id: "number-of-associated-line-items", name: "Number of Associated Line Items", type: "number" },
      { id: "priority", name: "Priority", type: "check" },
      { id: "record-id", name: "Record ID", type: "number" },
      { id: "record-source", name: "Record source", type: "check" },
      { id: "record-source-detail-1", name: "Record source detail 1", type: "text" },
      { id: "record-source-detail-2", name: "Record source detail 2", type: "text" },
      { id: "record-source-detail-3", name: "Record source detail 3", type: "text" },
      { id: "segment-list-membership", name: "Segment (List) membership", type: "check" },
      { id: "updated-by-user-id", name: "Updated by user ID", type: "check" },
      { id: "weighted-amount", name: "Weighted amount", type: "fx" },
      { id: "weighted-amount-in-company-currency", name: "Weighted amount in company currency", type: "fx" },
    ]
  },
  {
    category: "Rootline Metrics",
    items: [
      { id: "weighted-open-pipeline-in-company-currency", name: "Weighted open pipeline in company currency", type: "fx" },
    ]
  },
  {
    category: "Analytics history",
    items: [
      { id: "latest-traffic-source", name: "Latest Traffic Source", type: "fx" },
      { id: "latest-traffic-source-data-1", name: "Latest Traffic Source Data 1", type: "text" },
      { id: "latest-traffic-source-data-2", name: "Latest Traffic Source Data 2", type: "text" },
      { id: "latest-traffic-source-timestamp", name: "Latest Traffic Source Timestamp", type: "number" },
      { id: "original-traffic-source", name: "Original Traffic Source", type: "check" },
      { id: "original-traffic-source-drill-down-1", name: "Original Traffic Source Drill-Down 1", type: "text" },
      { id: "original-traffic-source-drill-down-2", name: "Original Traffic Source Drill-Down 2", type: "text" },
    ]
  },
];

