export const LAYOUT_CONSTANTS = {
  SIDEBAR_WIDTH: 200,
  TOPNAV_HEIGHT: 56,
  MOBILE_BREAKPOINT: 768,
} as const;

export const SIDEBAR_WIDTH_CSS = `${LAYOUT_CONSTANTS.SIDEBAR_WIDTH}px`;
export const TOPNAV_HEIGHT_CSS = `${LAYOUT_CONSTANTS.TOPNAV_HEIGHT}px`;
